name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy (contoh)
        run: echo "Simulasi deploy website"

      - name: Kirim Notifikasi ke Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.8193531713:AAHJqd37MKI_HvqI6ZXxaxn-TBeIt-EmSIw }}
          TELEGRAM_CHAT_ID: ${{ secrets.7704776010 }}
        run: |
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage \
            -d chat_id=$TELEGRAM_CHAT_ID \
            -d text="Website berhasil diupdate dari GitHub!"
